# Generated by Django 4.2.3 on 2023-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('fact_qliq_data1', models.IntegerField()),
                ('fact_qliq_data2', models.IntegerField()),
                ('fact_qoil_data1', models.IntegerField()),
                ('fact_qoil_data2', models.IntegerField()),
                ('forecast_qliq_data1', models.IntegerField()),
                ('forecast_qliq_data2', models.IntegerField()),
                ('forecast_qoil_data1', models.IntegerField()),
                ('forecast_qoil_data2', models.IntegerField()),
                ('on_date', models.DateField()),
            ],
        ),
    ]
